version: '3'
services:
  website:
    container_name: website
    build: 
      context: backend
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - "8080:8080"
    volumes:
      - ./backend/:/backend
  website-db:
    image: postgres
    restart: always
  
